Add power function and test to backend
google/TensorNetwork pull request #846
Opened 2020-10-01 02:57 UTC by wkostuch

First step as proposed in #840 to add support for the np.power function.

2020-10-01 13:15 UTC, alewis commented
Before code can be merged, it needs to "build", which means for example that pylint and pytest have to run successfully. You can tell whether your code has built properly by looking at the line marked "continuous-integration/travis-ci/pr", which will have a red X / green checkmark upon failure/success. The same symbols appear next to the PR in the PR list. 

If the code doesn't build, you can click Details on the same line to see which configurations have failed, and then click on any one of them to see the console output from each. In your case the error is quite simple: line 1001 in abstract_backend.py exceeds the maximum character limit of 80 characters.

2020-10-01 13:19 UTC, alewis requested changes
Looks good mostly! Fix the small formatting issues here and I'll merge.

2020-10-01 13:19 UTC, alewis commented on tensornetwork/backends/abstract_backend.py
> +      The tensor that is each element of a raised to the corresponding power in b.
Line too long

2020-10-01 13:19 UTC, alewis commented on tensornetwork/backends/abstract_backend.py
> +  def power(self, a: Tensor, b: Tensor) -> Tensor:
b should be allowed to be a scalar as well, in which case the output should be each element in a raised to b.

2020-10-01 13:19 UTC, alewis commented on tensornetwork/backends/abstract_backend.py
> +    raise NotImplementedError(f"Backend {self.name} has not implemented power.")
Add a newline at the end here

2020-10-01 13:19 UTC, alewis commented on tensornetwork/backends/backend_test.py
> +    backend.power(np.array([1, 2]), np.array([1, 2]))
Add a newline to the end of the file

2020-10-03 21:40 UTC, wkostuch commented on tensornetwork/backends/abstract_backend.py
> +      a: The tensor containing the bases.
I've made a few changes concerning the shape in the docstring, but I do think I'll be able to express the size conditions more clearly and concisely after the function is written.

2020-10-03 21:47 UTC, alewis approved these changes
Ok, looks good. Fix the build and I'll merge.

2020-10-03 21:47 UTC, alewis commented on tensornetwork/backends/abstract_backend.py
> +      a: The tensor containing the bases.
SGTM

2020-10-05 14:28 UTC, merged