Tensor svd
google/TensorNetwork pull request #876
Opened 2020-11-05 14:41 UTC by mganahl

make `tn.svd`  work with `BlockSparseTensor`

2020-11-06 15:35 UTC, Thenerdstation requested changes
Add a test. Otherwise LGTM

2020-11-10 21:18 UTC, alewis reviewed
What he said

2020-11-13 20:24 UTC, alewis approved these changes
Looks good to me, except for that one little thing

2020-11-13 20:24 UTC, alewis commented on tensornetwork/backends/symmetric/decompositions.py
> +        np.full(discarded_singvals[n].shape[0], fill_value=n, dtype=np.int16)
can we break this up?

2020-11-13 20:29 UTC, mganahl commented on tensornetwork/backends/symmetric/decompositions.py
> +        np.full(discarded_singvals[n].shape[0], fill_value=n, dtype=np.int16)
sure thing, is this better?

2020-12-02 07:24 UTC, merged